{
 "title": "Yandex Cloud Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Products With Related Issues",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (product) (yc_active_incidents) != 0 and yc_active_incidents{product!='up'}",
     "legendFormat": "{{ product }}"
    }
   ]
  },
  {
   "title": "Services Incident Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (product) (rate(yc_active_incidents[1m]))",
     "legendFormat": "{{ product }}"
    }
   ]
  },
  {
   "title": "Services status",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(yc_service_status) by (product)",
     "legendFormat": "{{ product }}"
    }
   ]
  },
  {
   "title": "Past Issues",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "yc_last_incidents_info >0", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}