global:
  scrape_interval: 15s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'yc-exporter'
    static_configs:
      - targets: ['exporter:5000']
